*** Variables ***
#Browsers
${BROWSER}    chrome

#Urls
${url}    https://www.saucedemo.com
${url_cart}    https://www.saucedemo.com/cart.html
${url_inventory}    https://www.saucedemo.com/inventory.html
${url_checkout_info}    https://www.saucedemo.com/checkout-step-one.html
${url_checkout_order}    https://www.saucedemo.com/checkout-step-two.html
${url_checkout_complete}    https://www.saucedemo.com/checkout-complete.html

# Product names
${name_tshirt_red}    Test.allTheThings() T-Shirt (Red)

# Product descriptions
${desc_backpack}    carry.allTheThings() with the sleek, streamlined Sly Pack that melds uncompromising style with unequaled laptop and tablet protection.
${desc_bike_light}    A red light isn't the desired state in testing but it sure helps when riding your bike at night. Water-resistant with 3 lighting modes, 1 AAA battery included.
${desc_bolt_tshirt}    Get your testing superhero on with the Sauce Labs bolt T-shirt. From American Apparel, 100% ringspun combed cotton, heather gray with red bolt.
${desc_fleece_jacket}    It's not every day that you come across a midweight quarter-zip fleece jacket capable of handling everything from a relaxing day outdoors to a busy day at the office.
${desc_tshirt_red}    This classic Sauce Labs t-shirt is perfect to wear when cozying up to your keyboard to automate a few tests. Super-soft and comfy ringspun combed cotton.

# Product price
${price_backpack}    $29.99
${price_bike_light}    $9.99
${price_bolt_tshirt}    $15.99
${price_fleece_jacket}    $49.99
${price_tshirt_red}    $15.99
