*** Variables ***
${sauce_labs_backpack_url}   https://www.saucedemo.com/inventory-item.html?id=4
${sauce_labs_onesie_url}   https://www.saucedemo.com/inventory-item.html?id=2
${sauce_labs_fleece_jacket_url}   https://www.saucedemo.com/inventory-item.html?id=5
${sauce_labs_bike_light_url}   https://www.saucedemo.com/inventory-item.html?id=0
${sauce_labs_bolt_tshirt_url}   https://www.saucedemo.com/inventory-item.html?id=1
${test_allthethings_tshirt_red_url}   https://www.saucedemo.com/inventory-item.html?id=3
